/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#904d00',
        'on-primary': '#ffffff',
        'primary-container': '#ff8c00',
        'on-primary-container': '#623200',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        'inverse-primary': '#ffb77d',
        secondary: '#b80049',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2165f',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#ffd9de',
        'secondary-fixed-dim': '#ffb2be',
        'on-secondary-fixed': '#400014',
        'on-secondary-fixed-variant': '#900038',
        tertiary: '#6a5f00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#beab00',
        'on-tertiary-container': '#473f00',
        'tertiary-fixed': '#f9e448',
        'tertiary-fixed-dim': '#dcc82b',
        'on-tertiary-fixed': '#201c00',
        'on-tertiary-fixed-variant': '#504700',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#faf9f6',
        'surface-dim': '#dbdad7',
        'surface-bright': '#faf9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'surface-container': '#efeeeb',
        'surface-container-high': '#e9e8e5',
        'surface-container-highest': '#e3e2e0',
        'surface-variant': '#e3e2e0',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#564334',
        'inverse-surface': '#2f312f',
        'inverse-on-surface': '#f2f1ee',
        outline: '#897362',
        'outline-variant': '#ddc1ae',
        'surface-tint': '#904d00',
        background: '#faf9f6',
        'on-background': '#1a1c1a',
        strava: '#FC4C02',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1280px',
        unit: '8px',
      },
      fontFamily: {
        lexend: ['Lexend', 'sans-serif'],
        newsreader: ['Newsreader', 'serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
